version: "3.1"

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
      PGDATA: /var/lib/postgresql/data
    networks:
      - webnet

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - webnet

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - db-data:/var/lib/mongo/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: db
    networks:
      - webnet

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    networks:
      - webnet

  app:
    container_name: app
    build: ./app
    restart: always
    depends_on:
      - "mongo"
      - "postgres"
    command:
      [
        "/wait-for-it.sh",
        "postgres:5432",
        "mongo:27017",
        "--",
        "npm",
        "run",
        "migrate",
        "up",
      ]
    ports:
      - "3000:3000"
    volumes:
      - ./app:/server
      - /app/node_modules
    networks:
      - webnet

volumes:
  db-data:
    driver: local

networks:
  webnet:
    driver: bridge
